services:
  - type: web
    name: gpu-race
    env: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 